requirejs.config({
    paths:{
        "jquery":"./src/libs/jquery-3.3.1",
        "goodsList":"./src/libs/jquery.goodsList",
        "index":"./src/model/index",
        "index2":"./src/model/index2",
        "login":"./src/model/login",
        "register":"./src/model/register",
        "cookie":"./src/libs/jquery.cookie",
    }
})